// Generated by tools/embed.py - edit the files in assets/, not this one.
#pragma once

static const char* kUserScript = R"USERSCRIPT(// ==UserScript==
// @name         Screen Share Sound (Firefox)
// @namespace    sharesound
// @version      1.1.0
// @description  Adds system audio to screen sharing in Firefox, which cannot capture it itself
// @match        https://discord.com/*
// @match        https://*.discord.com/*
// @match        http://127.0.0.1/*
// @match        http://localhost/*
// @run-at       document-start
// @grant        none
// ==/UserScript==

(function () {
  'use strict';

  var BRIDGE = 'http://127.0.0.1:47823';
  var CONNECT_TIMEOUT_MS = 2500;
  var VERSION = '1.1.0';

  // On the helper's own status page there is nothing to patch: just leave a mark
  // so the page can tell the user this script is installed.
  if (location.origin === BRIDGE) {
    var mark = function () {
      try { document.documentElement.dataset.sharesound = VERSION; } catch (e) {}
    };
    mark();
    document.addEventListener('DOMContentLoaded', mark);
    return;
  }
  var log = function (m, x) { try { console.log('[sharesound] ' + m, x === undefined ? '' : x); } catch (e) {} };

  // The worklet keeps a small jitter buffer: it waits for PREFILL before
  // starting, drops the oldest audio if the queue grows past MAX (a stalled
  // reader must not add permanent latency), and emits silence on underrun.
  function workletFactory() {
    class PCMPlayer extends AudioWorkletProcessor {
      constructor() {
        super();
        this.q = [];
        this.buffered = 0;
        this.cur = null;
        this.off = 0;
        this.prefill = 48000 * 0.10;
        this.max = 48000 * 0.35;
        this.started = false;
        this.port.onmessage = (e) => {
          const a = new Int16Array(e.data);
          this.q.push(a);
          this.buffered += a.length / 2;
          while (this.buffered > this.max && this.q.length > 1) {
            this.buffered -= this.q.shift().length / 2;
          }
        };
      }
      process(inputs, outputs) {
        const out = outputs[0];
        const L = out[0], R = out[1];
        const n = L.length;
        if (!this.started) {
          if (this.buffered < this.prefill) { L.fill(0); if (R) R.fill(0); return true; }
          this.started = true;
        }
        for (let i = 0; i < n; i++) {
          if (!this.cur || this.off >= this.cur.length) {
            this.cur = this.q.shift() || null;
            this.off = 0;
            if (!this.cur) {
              for (let j = i; j < n; j++) { L[j] = 0; if (R) R[j] = 0; }
              this.started = false;
              return true;
            }
          }
          L[i] = this.cur[this.off] / 32768;
          if (R) R[i] = this.cur[this.off + 1] / 32768;
          this.off += 2;
          this.buffered--;
        }
        return true;
      }
    }
    registerProcessor('sharesound-pcm', PCMPlayer);
  }

  var workletUrl = null;
  function getWorkletUrl() {
    if (!workletUrl) {
      var src = '(' + workletFactory.toString() + ')()';
      workletUrl = URL.createObjectURL(new Blob([src], { type: 'text/javascript' }));
    }
    return workletUrl;
  }

  // Opens the bridge and returns a live audio track, or null if the helper is
  // not running - in that case the screen share proceeds silently, as before.
  async function openBridgeTrack() {
    var ctx = new AudioContext({ sampleRate: 48000, latencyHint: 'playback' });
    var abort = new AbortController();
    var cleanup = function () {
      try { abort.abort(); } catch (e) {}
      try { ctx.close(); } catch (e) {}
    };
    try {
      await ctx.audioWorklet.addModule(getWorkletUrl());
      if (ctx.state === 'suspended') await ctx.resume();
      var node = new AudioWorkletNode(ctx, 'sharesound-pcm', {
        numberOfInputs: 0, numberOfOutputs: 1, outputChannelCount: [2]
      });
      var dest = ctx.createMediaStreamDestination();
      node.connect(dest);

      var firstChunk = null;
      var gotFirst = new Promise(function (resolve) { firstChunk = resolve; });

      (async function pump() {
        var backoff = 500;
        while (!abort.signal.aborted) {
          try {
            var r = await fetch(BRIDGE + '/pcm', { signal: abort.signal, cache: 'no-store' });
            if (!r.ok || !r.body) throw new Error('bridge http ' + r.status);
            var reader = r.body.getReader();
            backoff = 500;
            for (;;) {
              var res = await reader.read();
              if (res.done) break;
              if (firstChunk) { firstChunk(true); firstChunk = null; }
              node.port.postMessage(res.value.buffer, [res.value.buffer]);
            }
            log('bridge stream ended, reconnecting');
          } catch (e) {
            if (abort.signal.aborted) return;
            log('bridge error, retrying', String(e && e.message || e));
          }
          // the helper may be restarting; keep trying while the share is live
          await new Promise(function (r2) { setTimeout(r2, backoff); });
          backoff = Math.min(backoff * 2, 5000);
        }
      })();

      var ok = await Promise.race([
        gotFirst,
        new Promise(function (r3) { setTimeout(function () { r3(false); }, CONNECT_TIMEOUT_MS); })
      ]);
      if (!ok) { cleanup(); log('helper not reachable at ' + BRIDGE + ', sharing without sound'); return null; }

      var track = dest.stream.getAudioTracks()[0];
      track.addEventListener('ended', cleanup);
      return { track: track, cleanup: cleanup };
    } catch (e) {
      cleanup();
      log('bridge setup failed', String(e && e.message || e));
      return null;
    }
  }

  var MD = window.MediaDevices && window.MediaDevices.prototype;
  if (!MD || !MD.getDisplayMedia) return;

  var original = MD.getDisplayMedia;
  MD.getDisplayMedia = function (constraints) {
    var self = this;
    return original.call(self, constraints).then(async function (stream) {
      // Firefox returns video only; the app asked for audio and gets none.
      if (stream.getAudioTracks().length > 0) return stream;
      var bridge = await openBridgeTrack();
      if (!bridge) return stream;
      stream.addTrack(bridge.track);
      var video = stream.getVideoTracks()[0];
      if (video) video.addEventListener('ended', function () { bridge.cleanup(); });
      log('system audio attached to screen share');
      return stream;
    });
  };
  log('ready');
})();
)USERSCRIPT";

static const char* kStatusPage = R"STATUSPAGE(<!doctype html>
<meta charset="utf-8">
<title>sharesound</title>
<style>
  :root { color-scheme: dark light; }
  body { font: 15px/1.55 system-ui, -apple-system, Segoe UI, sans-serif;
         max-width: 660px; margin: 40px auto 80px; padding: 0 20px;
         background: #16171a; color: #e6e7ea; }
  h1 { font-size: 22px; margin: 0; }
  .sub { color: #9aa0a6; margin: 4px 0 24px; }
  .card { background: #1e2024; border: 1px solid #2b2e34; border-radius: 8px;
          padding: 14px 16px; margin: 10px 0; display: flex; gap: 12px; align-items: flex-start; }
  .dot { width: 10px; height: 10px; border-radius: 50%; background: #6b7280; margin-top: 6px; flex: none; }
  .dot.ok { background: #3ba55d; } .dot.bad { background: #ed4245; } .dot.wait { background: #faa81a; }
  .card b { display: block; margin-bottom: 2px; }
  .card small { color: #9aa0a6; }
  .meter { height: 8px; background: #2b2e34; border-radius: 4px; overflow: hidden; margin-top: 8px; }
  .meter div { height: 100%; width: 0; background: #3ba55d; transition: width .1s; }
  a.btn { display: inline-block; background: #5865f2; color: #fff; text-decoration: none;
          padding: 12px 20px; border-radius: 6px; margin: 18px 0 6px; font-weight: 600; }
  a.btn.done { background: #2b2e34; color: #9aa0a6; }
  ol { padding-left: 22px; } li { margin: 6px 0; }
  .hint { background: #1e2024; border-left: 3px solid #faa81a; padding: 12px 16px;
          border-radius: 0 6px 6px 0; margin: 16px 0; }
  code { background: #2b2e34; padding: 2px 6px; border-radius: 4px; font-size: 13px; }
  .lang { float: right; color: #9aa0a6; font-size: 13px; cursor: pointer; user-select: none; }
  footer { margin-top: 34px; color: #6b7280; font-size: 13px; }
  footer a { color: #6b7280; }
</style>

<span class="lang" id="lang"></span>
<h1>sharesound</h1>
<p class="sub" id="tagline"></p>

<div class="card"><span class="dot wait" id="d1"></span><div>
  <b id="t1"></b><small id="s1"></small></div></div>

<div class="card"><span class="dot wait" id="d2"></span><div>
  <b id="t2"></b><small id="s2"></small></div></div>

<div class="card"><span class="dot wait" id="d3"></span><div style="flex:1">
  <b id="t3"></b><small id="s3"></small>
  <div class="meter"><div id="bar"></div></div></div></div>

<a class="btn" id="install" href="/sharesound.user.js"></a>

<h3 id="h_steps"></h3>
<ol id="steps"></ol>

<div class="hint"><b id="h_echo"></b><div id="echo"></div></div>

<footer id="foot"></footer>

<script>
const T = {
  en: {
    tagline: 'System audio for screen sharing in Firefox.',
    t1: 'Helper', s1w: 'checking…', s1ok: 'running', s1bad: 'not responding — start sharesound.exe',
    t2: 'Userscript', s2w: 'checking…', s2ok: 'installed', s2bad: 'not detected — install it below, then reload this page (F5)',
    t3: 'Sound being captured', s3w: 'listening…', s3ok: 'sound is coming through',
    s3quiet: 'silence — play some music to test', s3bad: 'cannot read the audio stream',
    install: 'Install the userscript', installed: 'Userscript already installed',
    h_steps: 'Setup',
    steps: [
      'Install <a href="https://addons.mozilla.org/firefox/addon/tampermonkey/">Tampermonkey</a> in Firefox.',
      'Click the blue button above, then <b>Install</b> in the tab that opens — and reload this page afterwards, so the check above turns green.',
      'Reload your Discord tab (Ctrl+R).',
      'Start a screen share — the sound now goes with it.'
    ],
    h_echo: 'Will other people hear themselves?',
    perapp: 'Your Windows can capture per app. Run <code>sharesound.exe --exclude firefox.exe</code> and callers are excluded automatically.',
    separate: (d) => 'Capture takes everything playing on <b>' + d + '</b>, including the voices Discord plays to you — so callers would hear themselves. Fix: in Discord open <b>Settings → Voice &amp; Video</b> and set <b>Output Device</b> to your headphones by name, instead of <i>Default</i>.',
    stuck: 'You have one output device and Windows 10 older than build 20348, so call audio cannot be separated: people will hear themselves while they speak. Fixes: upgrade to Windows 11, or install any virtual audio device (VB-Cable, VoiceMeeter, FxSound), make it the default, and point Discord at your real headphones.',
    foot: 'Runs only on your computer. Nothing is uploaded anywhere.'
  },
  ru: {
    tagline: 'Звук при демонстрации экрана в Firefox.',
    t1: 'Программа', s1w: 'проверяю…', s1ok: 'работает', s1bad: 'не отвечает — запустите sharesound.exe',
    t2: 'Скрипт для браузера', s2w: 'проверяю…', s2ok: 'установлен', s2bad: 'не найден — установите его ниже, затем обновите эту страницу (F5)',
    t3: 'Звук захватывается', s3w: 'слушаю…', s3ok: 'звук идёт',
    s3quiet: 'тишина — включите музыку для проверки', s3bad: 'не удаётся прочитать звук',
    install: 'Установить скрипт', installed: 'Скрипт уже установлен',
    h_steps: 'Установка',
    steps: [
      'Поставьте <a href="https://addons.mozilla.org/firefox/addon/tampermonkey/">Tampermonkey</a> в Firefox.',
      'Нажмите синюю кнопку выше, затем <b>Install</b> во вкладке, которая откроется — и обновите эту страницу, чтобы проверка выше стала зелёной.',
      'Перезагрузите вкладку Discord (Ctrl+R).',
      'Запускайте демонстрацию экрана — звук теперь идёт вместе с ней.'
    ],
    h_echo: 'Будут ли собеседники слышать сами себя?',
    perapp: 'Ваша Windows умеет захватывать звук по приложениям. Запустите <code>sharesound.exe --exclude firefox.exe</code> — и голоса собеседников в стрим не попадут.',
    separate: (d) => 'Захватывается всё, что играет через <b>' + d + '</b>, включая голоса, которые Discord проигрывает вам, — поэтому собеседники услышат себя. Решение: в Discord откройте <b>Настройки → Голос и видео</b> и в поле <b>Устройство вывода</b> выберите свои наушники по названию вместо <i>По умолчанию</i>.',
    stuck: 'У вас одно устройство вывода и Windows 10 старее сборки 20348, поэтому отделить звук разговора нельзя: собеседники будут слышать себя, когда говорят. Варианты: обновиться до Windows 11 или поставить любое виртуальное аудиоустройство (VB-Cable, VoiceMeeter, FxSound), сделать его устройством по умолчанию, а в Discord выбрать реальные наушники.',
    foot: 'Работает только на вашем компьютере. Никуда ничего не отправляется.'
  }
};

// A Russian-localised Firefox often still reports navigator.language as en-US,
// so check every language the browser lists, and remember a manual choice.
function detectLang() {
  try {
    var saved = localStorage.getItem('sharesound.lang');
    if (saved === 'ru' || saved === 'en') return saved;
  } catch (e) {}
  var list = (navigator.languages && navigator.languages.length)
    ? navigator.languages : [navigator.language || 'en'];
  for (var i = 0; i < list.length; i++) {
    if (/^ru/i.test(list[i])) return 'ru';
  }
  try {
    if (/^(Europe\/(Moscow|Samara|Kaliningrad|Volgograd|Saratov|Kirov|Astrakhan|Ulyanovsk|Minsk)|Asia\/(Yekaterinburg|Novosibirsk|Krasnoyarsk|Irkutsk|Vladivostok|Omsk|Barnaul|Tomsk|Novokuznetsk|Chita|Yakutsk|Magadan|Sakhalin|Kamchatka|Anadyr|Almaty|Tashkent|Bishkek))/
        .test(Intl.DateTimeFormat().resolvedOptions().timeZone || '')) return 'ru';
  } catch (e) {}
  return 'en';
}
let lang = detectLang();
function render() {
  const t = T[lang];
  document.getElementById('lang').textContent = lang === 'ru' ? 'English' : 'Русский';
  document.getElementById('tagline').textContent = t.tagline;
  for (const k of ['t1', 't2', 't3', 'h_steps', 'h_echo']) document.getElementById(k).textContent = t[k];
  document.getElementById('steps').innerHTML = t.steps.map(x => '<li>' + x + '</li>').join('');
  document.getElementById('foot').textContent = t.foot;
  refresh();
}
document.getElementById('lang').onclick = () => {
  lang = lang === 'ru' ? 'en' : 'ru';
  try { localStorage.setItem('sharesound.lang', lang); } catch (e) {}
  render();
};

function set(n, state, text) {
  document.getElementById('d' + n).className = 'dot ' + state;
  document.getElementById('s' + n).textContent = text;
}

function refresh() {
  const t = T[lang];
  set(1, 'wait', t.s1w); set(2, 'wait', t.s2w); set(3, 'wait', t.s3w);

  fetch('/health').then(r => r.json())
    .then(h => set(1, 'ok', t.s1ok + ' · ' + h.mode))
    .catch(() => set(1, 'bad', t.s1bad));

  // the userscript tags this page when it is installed
  const installed = !!document.documentElement.dataset.sharesound;
  set(2, installed ? 'ok' : 'bad', installed ? t.s2ok : t.s2bad);
  const btn = document.getElementById('install');
  btn.textContent = installed ? t.installed : t.install;
  btn.className = installed ? 'btn done' : 'btn';

  fetch('/doctor').then(r => r.json()).then(d => {
    const e = document.getElementById('echo');
    if (d.verdict === 'perapp') e.innerHTML = t.perapp;
    else if (d.verdict === 'separate-device') e.innerHTML = t.separate(d.defaultDevice);
    else e.innerHTML = t.stuck;
  }).catch(() => {});
}

// Live level meter: reads the same stream the browser will use, so seeing the
// bar move proves the whole chain works.
async function meter() {
  const t = () => T[lang];
  try {
    const r = await fetch('/pcm');
    const reader = r.body.getReader();
    let quietFor = 0;
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      const pcm = new Int16Array(value.buffer, 0, value.byteLength >> 1);
      let peak = 0;
      for (let i = 0; i < pcm.length; i += 7) { const v = Math.abs(pcm[i]); if (v > peak) peak = v; }
      const norm = peak / 32768;
      document.getElementById('bar').style.width = Math.min(100, norm * 140) + '%';
      if (norm > 0.005) { quietFor = 0; set(3, 'ok', t().s3ok); }
      else if (++quietFor > 12) set(3, 'wait', t().s3quiet);
    }
  } catch (e) {
    set(3, 'bad', T[lang].s3bad);
  }
}

document.getElementById('install').addEventListener('click', () => {
  // Tampermonkey only applies a script to fresh page loads, so the check above
  // stays red until this page is reloaded - say so instead of looking broken.
  setTimeout(() => {
    const t = T[lang];
    set(2, 'wait', lang === 'ru'
      ? 'после установки обновите эту страницу (F5)'
      : 'after installing, reload this page (F5)');
  }, 1500);
});

render();
meter();
</script>
)STATUSPAGE";
