#!/usr/bin/env python3
"""Generates assets.h from the files in assets/ so the helper can serve them.

The userscript is the real source of truth in assets/sharesound.user.js; this
just wraps it in a raw string literal. Run after editing either asset:

    python tools/embed.py
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, 'assets')
OUT = os.path.join(ROOT, 'assets.h')

FILES = [
    ('kUserScript', 'sharesound.user.js', 'USERSCRIPT'),
    ('kStatusPage', 'status.html', 'STATUSPAGE'),
]

HEADER = """// Generated by tools/embed.py - edit the files in assets/, not this one.
#pragma once
"""


def main():
    parts = [HEADER]
    for name, filename, delim in FILES:
        path = os.path.join(ASSETS, filename)
        with io.open(path, encoding='utf-8') as f:
            body = f.read()
        if ')%s"' % delim in body:
            sys.exit('%s contains the raw-string delimiter )%s"' % (filename, delim))
        parts.append('\nstatic const char* %s = R"%s(%s)%s";\n' % (name, delim, body, delim))
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(parts))
    print('wrote %s (%d bytes)' % (os.path.relpath(OUT, ROOT), os.path.getsize(OUT)))


if __name__ == '__main__':
    main()
